momentohq/client-sdk-go

.github/workflows/ci_cd.yml
.github/workflows/golangci-lint.yml
.github/workflows/manual_release.yml
README.md

Note:
- Need to update the example link once https://github.com/momentohq/client-sdk-examples/pull/69 is merged
Closes #12

chore: Update readme

---

Makefile
README.md
go.mod
go.sum
internal/models/requests.go
internal/resolver/end_point_resolver.go
internal/services/scs_control_service.go
internal/services/scs_data_service.go
momento/cache_operation_requests.go
momento/error.go
momento/simple_cache_client.go
momento/simple_cache_client_test.go

@poppoerika I sat down played with sdk a bit more after latest error changes and made few tweaks to help with end user usability and code readability in few spots. Also tried to write good example of table test set up for reference. Open to changing any parts so please let me know what you think or if we can improve further after looking over.
Closes #16

feat: usability improvements and testing updates

---

internal/momentoerrors/scs_errors.go
internal/utility/utility.go
momento/error.go
momento/simple_cache_client.go
momento/simple_cache_client_test.go

- Added more detailed tests for control and data operations.
- Updated Momento and MomentoSvc errors' names
- Added a checker function to make sure key/value are not `nil`
Closes #3

chore: Add more detailed tests

---

momento/cache_operation_requests.go
momento/cache_operation_responses.go
momento/error.go
momento/simple_cache_client.go

These documentation will be reflected to our package [here](https://pkg.go.dev/github.com/momentohq/client-sdk-go@v0.2.1/momento#section-documentation).
Closes #17

chore: Add documentation for momento package

---

README.template.md

Updated `README` template to provide Go SDK Error handling. 
Also cleaned up the requirements section.
Closes #70

chore: update `README` template

---

examples/list-example/main.go
incubating/list_requests.go
incubating/list_responses.go
incubating/simple_cache_client.go
internal/models/list_requests.go
internal/models/list_responses.go
internal/services/scs_data_list_service.go

Finishes out the list operations.

chore: list ops part 2

---

momento/pub_sub_test.go
momento/simple_cache_client_test.go

fix: Ensure tests clean up their caches.

---

examples/sortedset-example/main.go
momento/sorted_set_fetch.go
momento/sorted_set_put.go

As per the Valentines Day Name Massacre.
Close #126

feat!: Rename SortedSet Name -> Value

---

momento/sorted_set_fetch.go
momento/sorted_set_remove.go

feat: also makes fetch and remove accept values for props as well

fix: sorted set remove request

---

README.template.md

You'd always want to check the response from a Get, but you can ignore it with a Set.

docs: Correct min Go version. Provide a more realistic error handling example.

---

examples/sortedset-example/main.go
momento/sorted_set_put.go
momento/sorted_set_test.go

Complete tests for sorted sets.
* Verifies that collectionTTLs work, Closes #116.
* SortedSetFetch took a surprising SortedSetScoreRequestElement. Closes #195

test: SortedSet

---

momento/dictionary_test.go
momento/list_test.go
momento/pubsub_test.go
momento/requester.go
momento/scalar_test.go
momento/set_test.go
momento/simple_cache_client.go
momento/sorted_set_get_rank.go
momento/sorted_set_increment_score.go
momento/sorted_set_test.go

This commit adds validation to prevent nil values in request structs and adds testing to verify the added validation across request types.
Addresses #192 and #178

chore: audit and test for nils

---

config/configurations.go
config/grpc-configuration.go
config/transport_strategy.go

feat: removes maxIdle and maxSessionMem from client config for now

---

momento/sorted_set_get_score.go
momento/sorted_set_test.go
responses/sorted_set_get_score.go

Also
* SortedSetScoreHit ->SortedSetScore and a simple type alias.
* It can potentially be reused for other methods which take/return scores.
Closes #186
For #197 
For #167

feat!: SortedSetGetScore -> SortedSetGetScores

---

momento/get.go
momento/simple_cache_client.go
responses/get.go

I somehow managed to miss the `get` operation 😅

fix: missed refactoring get responses somehow

---

examples/dictionary-example/main.go
examples/list-example/main.go
examples/pubsub-example/main.go
examples/scalar-example/main.go
examples/set-example/main.go

Updated all the examples under `examples`.
We can get https://github.com/momentohq/client-sdk-go/pull/224 and https://github.com/momentohq/client-sdk-go/pull/228 as well @pgautier404! 
I will update this PR as both PRs get merged and then we can merge this PR and make a release possibly?

chore: update examples

---

momento/dictionary_test.go
momento/list_test.go
momento/requester.go
momento/sorted_set_get_rank.go
momento/sorted_set_increment_score.go
momento/sorted_set_test.go

The original issue with DictionaryFetch returning `""` as `nil` seems to be gone. 🤔 
* Validate all values the same: can't be nil, can be empty.
* Add tests for empty values.
Closes #226

fix: All values can be blank.

---

momento/sorted_set_get_rank.go
momento/sorted_set_test.go

The Order argument is broken on the back-end.
https://github.com/momentohq/storage-store/issues/169
Once that's fixed, this is ready.
Closes #179

feat: SortedSetGetRank Order argument.

---

internal/grpcmanagers/data_manager.go
internal/grpcmanagers/ping_manager.go
internal/models/requests.go
internal/services/scs_ping_service.go
momento/cache_client.go
momento/ping_test.go
responses/ping.go

This commit adds a gRPC ping client that implements a `Ping` method, exposed through the cache client.

feat: add ping

---

momento/cache_client.go
momento/sorted_set_put_element.go
momento/sorted_set_put_elements.go
momento/sorted_set_test.go
responses/sorted_set_put.go
responses/sorted_set_put_element.go
responses/sorted_set_put_elements.go

- refactor: rename `SortedSetPut` response include `Elements` suffix
- feat: add `sortedSetPutElement` method, request, and response
TODO for future PR: tests

feat: implement `sortedSetPutElement`

---

examples/pubsub-example/main.go

Added comment before main section so people know why the cacheClient object is used.

chore: Update main.go

---

momento/cache_client.go
momento/scalar_test.go
momento/set_if_not_exists.go
responses/set_if_not_exists.go

Added implementation for ```SetIfNotExists``` with tests. Commit also exposes the API to our SDK once we release it.

feat: impl and expose SetIfNotExists API to clients/sdk

---

momento/topic_client_test.go
momento/topic_subscription.go

Addresses a bug where a client might have `canceled` the context they used to poll for a topic subscription.

fix: return if the context was cancelled while polling for subscription items

---

momento/cache_client.go
momento/set_pop.go
momento/set_test.go
responses/set_pop.go

Addresses [#470](https://github.com/momentohq/dev-eco-issue-tracker/issues/470) by adding SetPop to the SDK.

feat: add SetPop

---

README.md

This reverts commit 1e7c506c0888c46557b9b32b409ef7adb0832642.
Realized after merging this edited README directly not template 🤦 .

chore: revert `1e7c506`

---

internal/grpcmanagers/data_manager.go
momento/batch_set_get_test.go
momento/cache_client.go
momento/get_batch.go
momento/set_batch.go
momento/value.go
responses/get_batch.go
responses/set_batch.go

Adds getBatch and setBatch methods that are built into the CacheClient

feat: add getBatch and setBatch methods

---

examples/doc-examples-go-apis.go

adds caching pattern examples to be consumed downstream in dev docs

feat: add caching pattern examples

---

.github/workflows/on-pull-request.yml
Makefile
examples/doc-examples-go-apis.go
examples/docs-examples/main.go
examples/storage-cheat-sheet/main.go

Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/944
- Adds storage client snippets and a cheat sheet for dev docs 
- Fixes Makefile target for building examples
- Adds Makefile target and github actions step for running the dev docs snippets in CI

chore: add dev docs snippets for storage client

---

.github/workflows/on-pull-request.yml
internal/grpcmanagers/auth_manager.go
internal/models/requests.go
internal/permissions.go
momento/auth_client.go
momento/auth_client_test.go
momento/generate_api_key.go
momento/internal_auth_client.go
momento/permission_scope.go
momento/permission_scope_test.go
responses/auth/generate_api_key.go
utils/expiration.go
utils/validators.go

Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/954
[Follow up PR](https://github.com/momentohq/public-dev-docs/pull/1104) will update dev docs (API matrix is out of date, did not include GenerateDisposableToken which was already implemented)

feat: implement GenerateApiKey

---

.github/workflows/update-and-generate-protos.yml

There were a couple typos in the previous commit. This corrects those.

ci: correct pr body wording in update and generate protos workflow

---

Makefile

Fixes a formatting inconsistency in the Makefile.

chore: fix formatting in Makefile

---

CONTRIBUTING.md

Tweak the contributing documentation in order to trigger another
release.

chore: update contributing documentation

---

internal/retry/eligibility_strategy.go

Per discussions, we want to retry on cancelled to support retries
during a deployment.
work towards #1071

feat: retry on cancelled status code

---

momento/replica_reads_test.go
momento/test_helpers/shared_context.go

- Add replica-reads test using balanced read concern.
https://github.com/momentohq/dev-eco-issue-tracker/issues/1049

feat: add replica-reads test

---

Makefile

- https://github.com/momentohq/dev-eco-issue-tracker/issues/1068
- https://github.com/momentohq/client-sdk-javascript/pull/1472

chore: add test-http-service target

---

examples/loadgen/main.go

Augments the load generator to track and report cancelled errors. Also
sets the cache client log level to debug.

chore(loadgen): track cancelled errors in the load generator

---

momento/pubsub_client.go
momento/topic_client.go
momento/topic_subscription.go

Previously the internal subscribe client was typed as
`grpc.ClientStream`, which is a low-level type and not intended for
use when dealing with streams.
We refactor the code to type with generated, specific type
`Pubsub_SubscribeClient`. We refactor the variable names to reflect
this, preferring the name `subscribeClient`. With that we use the
higher level `Recv` method instead of `RecvMsg`.

refactor: type internal subscribe client and prefer `Recv`

---

internal/grpcmanagers/grpc-channel-options.go

- Adds a flag to disable the dynamic DNS service config
https://github.com/momentohq/dev-eco-issue-tracker/issues/1132

fix: disable dynamic DNS service config

---

.github/workflows/on-push-to-main.yml

This commit fixes the make target to run tests on push to main.

chore: fix make target in github workflow

---

momento/scalar_with_hash_test.go

Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1209
To avoid canary failures, we'll merge these new integration tests after we've confirmed the new apis have been rolled out to all prod cells.

chore: add integration tests for new get/set if hash methods
