- .github/workflows/build.yml
- .github/workflows/manual_release.yml
- .github/workflows/on-push-to-main.yml
- internal/services/scs_control_service.go
- internal/services/scs_data_service.go
- momento/simple_cache_client.go
- momento/simple_cache_client_test.go
Following what the pubsub public APIs do, allow users to pass their own `context.Context` to the public cache APIs rather than injecting our own context under the hood.
Closes #47
> chore: add `context.Context` as a parameter to public APIs

- auth/credential_provider.go
This adds a `NewStringMomentoTokenProvider` method to construct a credential provider from an auth token.
> chore: add a string token provider for use with canary

- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- .github/workflows/test.yml
* Commitlint can only run as part of a PR
* Put verifying and generating the readmes back where they were. It doesn't seem right, but that's how other repos do it.
> fix: Push to main.

- examples/sortedset-example/main.go
- incubating/simple_cache_client.go
- incubating/sortedset_requests.go
- internal/models/sortedset_requests.go
- internal/services/scs_data_sorted_set_service.go
Our official naming convention requires `elements` to be put into a `collection`.
Therefore, I updated the word `item(s)` to `element(s)` in the types used in `sorted set`.
Also, I updated some wording in the sorted set demo.
> chore: update word `item(s)` to `element(s)`

- .github/workflows/on-push-to-main.yml
- momento/pub_sub_test.go
I thought it would figure that out from the template.
Also requires momentohq/standards-and-practices#51
> fix: Set the output when generating the contributing file.

- momento/common.go
- momento/delete.go
- momento/get.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_fetch.go
- momento/list_length.go
- momento/list_pop_back.go
- momento/list_pop_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/list_remove_value.go
- momento/requester.template
- momento/scs_data_client.go
- momento/set.go
- momento/sorted_set_fetch.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_get_score.go
- momento/sorted_set_increment.go
- momento/sorted_set_put.go
- momento/sorted_set_remove.go
This commit corrects the argument order to `makeGrpcRequest()` such that the context is passed first.
> fix: make sure context is the first argument when it's passed

- README.template.md
- examples/go.mod
- examples/list-example/main.go
- examples/main.go
- examples/sortedset-example/main.go
- momento/delete.go
- momento/get.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_fetch.go
- momento/list_length.go
- momento/list_pop_back.go
- momento/list_pop_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/list_remove_value.go
- momento/set.go
- momento/simple_cache_client.go
- momento/simple_cache_client_test.go
- momento/sorted_set_fetch.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_increment.go
- momento/sorted_set_put.go
- momento/sorted_set_remove.go
- momento/topic_publish.go
> feat: Change back to returning responses as pointers

- momento/requester.go
Make it clear the file is all about the requester interface, not a jumble of common functions. Document it for internal use.
Closes #113
> refactor: common.go -> requester.co

- examples/list-example/main.go
- examples/main.go
- examples/pubsub-example/main.go
- examples/sortedset-example/main.go
- momento/cache_requests.go
- momento/create_cache.go
- momento/delete_cache.go
- momento/list_caches.go
- momento/pub_sub_test.go
- momento/simple_cache_client.go
- momento/simple_cache_client_test.go
The one oddball is ListCaches(). It seems like it should only ever return one response (as Go is not returning error responses) so making the user do the type switch seems unnecessary. But that's the interface pattern. 🤷 And it would make it the oddball that doesn't return an interface.
Closes #101
> feat!: Ensure all methods return a response.

- momento/delete.go
- momento/get.go
- momento/list_caches.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_fetch.go
- momento/list_length.go
- momento/list_pop_back.go
- momento/list_pop_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/list_remove_value.go
- momento/set.go
- momento/sorted_set_fetch.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_get_score.go
- momento/sorted_set_increment.go
- momento/sorted_set_put.go
- momento/sorted_set_remove.go
This commit contains fixes to quiet IDE warnings, particularly warnings about having methods on both pointer and value receivers for a given type.
> chore: standardize receivers for request type functions

- momento/pub_sub_test.go
I'm trying to track down what's still leaving caches around.
> fix: Make sure the pubsub tests clean up after themselves even if they fail.

- momento/get.go
- momento/list_fetch.go
- momento/list_length.go
- momento/list_pop_back.go
- momento/list_pop_front.go
- momento/requester.go
- momento/scs_data_client.go
- momento/sorted_set_fetch.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_get_score.go
Unfortunately I can't figure out how to get the actual type of the response. At least now it's wrapped in a function so it can be easily improved, and it eliminates the special case in makeRequest().
Close #114
> feat: Improve the "unexpected GRPC response error"

- internal/momentoerrors/scs_errors.go
- momento/error.go
This commit brings the Momento error codes in line with the standards and practices doc.
> fix: add missing error codes and fix mappings

- momento/control_test.go
- momento/momento_suite_test.go
- momento/pubsub_test.go
- momento/scalar_test.go
- momento/set_test.go
- momento/simple_cache_client_test.go
- momento/test_helpers/shared_context.go
* Extract test setup into SharedContext.
* Extract custom matchers into a shared location.
This makes tests easier to write consistently and understandably. What is shared and what is local is made clear.
> refactor: Extract test shared context

- .github/workflows/test.yml
- CONTRIBUTING.template.md
It's no longer used by the tests, it chooses its own unique cache names to enable parallel testing.
For #187
> fix: Remove references to TEST_CACHE_NAME

- momento/list_push_back.go
- momento/requester.go
- momento/set_add_elements.go
- momento/set_remove_elements.go
- momento/sorted_set_get_score.go
- momento/sorted_set_remove.go
This commit validates values in the `process` methods (e.g., `processValue`) to ensure they are not `nil` and, if they are, returns an `InvalidArgument` error.
> fix: add validation to 'prepare' methods in requestor

- momento/list_test.go
- momento/momento_suite_test.go
More testing is on the way for all collection data types regarding struct defaults, nil requests, and related issues. This commit brings the list type testing to parity with the other types to this point.
> chore: add list testing

- README.md
- README.template.md
- examples/dictionary-example/main.go
- examples/list-example/main.go
- examples/pubsub-example/main.go
- examples/set-example/main.go
- examples/sortedset-example/main.go
- momento/dictionary_fetch.go
- momento/dictionary_get_fields.go
- momento/dictionary_increment.go
- momento/dictionary_set_field.go
- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/requester.go
- momento/requester.template
- momento/set_add_element.go
- momento/set_add_elements.go
- momento/set_test.go
- momento/simple_cache_client.go
- momento/simple_cache_client_test.go
- momento/sorted_set_increment_score.go
- momento/sorted_set_put.go
- momento/sorted_set_test.go
- momento/test_helpers/shared_context.go
- utils/collection_ttl.go
Rename the following:
- `SimpleCacheClient` to `CacheClient`
- dictionary `items` to `elements`
- `CollectionTTL` to `CollectionTtl` 
Closes #183 
Closes #184 
Closes #185
> chore: update a few names

- .gitignore
- momento/pubsub_test.go
- momento/simple_cache_client.go
Testing topic name validation revealed some problems.
* TopicSubscribe and TopicPublish were not validating names.
* TopicSubscribe did not error when the cache did not exist.
* TopicPublish was not wrapping its error.
Closes #198
> fix: Topic name and cache validation

- momento/dictionary_increment.go
- momento/dictionary_set_field.go
- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/set_add_element.go
- momento/set_add_elements.go
- momento/set_test.go
- momento/simple_cache_client.go
- momento/sorted_set_increment_score.go
- momento/sorted_set_put.go
- momento/sorted_set_test.go
To follow up [this renaming PR](https://github.com/momentohq/client-sdk-go/pull/203), this is to update `CollectionTtl` to `Ttl` in collection request types.
This way, users will pass a `Ttl` struct to a property named `Ttl`.
This decision is to be consistent with other SDKs and this PR's main goal.
Closes #207
> chore: rename `CollectionTtl` to `Ttl` in request types

- examples/pubsub-example/main.go
- momento/pubsub_client.go
- momento/pubsub_test.go
- momento/topic_publish.go
- momento/topic_subscription.go
- momento/topic_value.go
- momento/value.go
We need TopicValue because in the future topics may accept more value types than normal methods. But there's no need for different string and bytes types.
* Replace TopicValueString and TopicValueBytes with the existing String and Bytes.
* String and Bypes implement TopicValue.
Closes #171
> feat!: Make TopicValue easier to work with.

- momento/dictionary_increment.go
- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/list_concatenate_back.go
- momento/list_concatenate_front.go
- momento/list_push_back.go
- momento/list_push_front.go
- momento/requester.go
- momento/scalar_test.go
- momento/set.go
- momento/set_add_elements.go
- momento/set_test.go
- momento/simple_cache_client.go
- momento/simple_cache_client_test.go
- momento/sorted_set_increment_score.go
- momento/sorted_set_put.go
- momento/sorted_set_test.go
- momento/test_helpers/shared_context.go
This commit changes the `NewCacheClient` constructor method so it accepts arguments for configuration, credential provider, and default TTL as discrete values instead of bundling them in a struct. This prevents users from passing in an empty struct with golang default values that guarantee the user a broken client. It also normalizes `TTL` -> `Ttl` in camel cased identifiers.
> chore: convert cache client constructor to accept args

- examples/list-example/main.go
Closes https://github.com/momentohq/client-sdk-go/issues/175
> chore: make sure all example methods accept momento.Value args

- Makefile
This will catch when the examples won't compile.
> chore: Lint the example code.

- Makefile
This reverts commit f2c2397be875cde9a4018f0bf76ee62a90ecf3d9.
@schwern going to revert this for time being causing some churn on prs. Im going to come back will try re-add back in tomorrow and come up w/ better flow for updating examples and running linting.
> chore: revert Lint the example code

- auth/credential_provider.go
- auth/credential_provider_test.go
- config/config.go
- config/configurations.go
- go.work
- momento/simple_cache_client_test.go
- momento/test_helpers/shared_context.go
This commit reduces the set of exported symbols from the `auth` and `config` packages down to only those that users need to interact with. It also panics on an error that it was previously swallowing when constructing the CredentialProvider for the tests so users will now see a clear explanation of the failure. 
Addresses #176 and #187
> fix: navigable auth and config packages

- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/requester.go
- momento/simple_cache_client.go
- momento/test_helpers/shared_context.go
- momento/value.go
This commit introduces an `Element` type that contains an `ElemField` and `ElemValue`, both of which use our `Value` type. This type is for use with `DictionarySetFields` and allows users to provide byte and string fields and values, as opposed to go's built-in `map` which disallows byte slice keys. It also includes helper functions to convert from a few different types of maps to `[]Element`. Finally, the shared test context code has been modified to prepend test caches with `golang-` for easy identification of the source of stranded caches.
> fix: use alternative data structure for dict ops

- momento/dictionary_test.go
- momento/list_test.go
- momento/scalar_test.go
- momento/set_test.go
- momento/topic_client.go
- momento/topic_value.go
This commit contains a grab bag of small fixes encountered while auditing response types for #193, mostly explicit checks for `miss` types to ensure they come in as pointers.
> chore: verify pointer responses

- momento/cache_client.go
- momento/requester.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_get_scores.go
- momento/sorted_set_increment_score.go
- momento/sorted_set_remove.go
- momento/sorted_set_test.go
- responses/sorted_set_get_rank.go
- responses/sorted_set_increment_score.go
* Everything takes Value or Values
* Not ElementValue, there's nothing special about sorted set values.
* SortedSetRemove only takes values.
* The some/all flag was complex, use `client.delete`.
* Use the usual value validation.
* SortedSetIncrementScoreSuccess
* Add Score()
* Remove public member.
* Make it a type conversion.
* SortedSetGetRankHit
* Add Rank()
* Remove public member.
* Make it a type conversion.
Closes #167 
Closes #204 
Closes #168
> feat!: Sortedset inconsistencies

- momento/sorted_set_get_scores.go
- momento/sorted_set_test.go
- responses/sorted_set_get_scores.go
* SortedSetGetScoresHit
* Make members private
* Add Scores() accessor
* SortedSetScoreElement 0> SortedSetGetScore
* They're not elements, and they're not just scores.
This should be the last SortedSet breaking change.
> feat!: SortedSetGetScores polish.

- momento/cache_client.go
- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/requester.go
- momento/value.go
* Element -> DictionaryElement
* Distinguish it from every other kind of "element".
* ElemField/ElemValue -> Field/Value
* We no longer prefix struct members. A field is a field, a value is a value.
I think this is the last naming issue.
> feat!: Normalize dictionaries.

- config/logger/builtin-logger.go
- config/logger/momento-logger.go
- config/logger/noop-momento-logger.go
This commit exports the `LogLevel` const from `momento-logger` so users can access it.
> fix: export LogLevel

- momento/sorted_set_fetch.go
- momento/sorted_set_test.go
Allen pointed out that in some places for sorted sets we were
using the term Rank, while in other places we were using the
term Index.  This commit changes occurrences of Index to Rank.
This mirrors what we did in the node.js SDK.
> feat: use "rank" terminology consistently for sorted sets

- CONTRIBUTING.template.md
On MacOS, two developers had to add the mentioned path to the PATH
environment variable so go could find the dev tools.
> docs: macos contributing note about go path

- config/configurations.go
- momento/cache_client_test.go
This changes the signatures that we use to configure logging for the client.  Prior to this commit the constructors were taking a vararg array of loggerFactories, which might lead users to think they could pass more than one.
This commit adds alternate constructors that accept a single logger factory instead.
> feat: tweaks to how we configure logging

- momento/cache_client.go
- momento/sorted_set_remove_elements.go
- momento/sorted_set_test.go
- responses/sorted_set_remove.go
Also renames request, response, and interface as appropriate.
> refactor: rename `SortedSetRemove` to `SortedSetRemoveElements`

- config/logger/momento_default_logger/momento-default-logger.go
The default logger was calling Printf with its varargs array without spreading it back out, meaning that the whole array would get formatted into the first %s.  This spreads the varargs back out properly.
> fix: default logger wasn't spreading varargs properly

- examples/dictionary-example/main.go
- momento/cache_client.go
- momento/dictionary_set_fields.go
- momento/dictionary_test.go
- momento/requester.go
Also adds an alias DictionaryElementsFromMap that is a short-hand
for the MapStringString variant.
> chore: rename ElementsFromMap* to DictionaryElementsFromMap*

- momento/test_helpers/shared_context.go
This commit uses the Noop logger for testing to suppress logging noise in test output.
> fix: use Noop logger for testing

- .github/workflows/manual_release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
Updates project badges to stable, sets semrel plugin to no
longer use pre-release versions
> feat: release 1.0

- momento/requester.go
- momento/sorted_set_fetch_by_rank.go
- momento/sorted_set_put_elements.go
- momento/sorted_set_test.go
- responses/sorted_set_fetch.go
This commit adds testing for sorted set functionality as well as validation for sorted set "by rank" indexes. It also validates values in `SortedSetPutElements` and errors on nils.
> chore: sorted set testing followup

- .github/workflows/test.yml
- Makefile
- examples/set-example/main.go
- examples/sortedset-example/main.go
- Added a step to run the examples except the loadgen (I'm not sure if we want to run the script every time...) to make sure all the examples are up-to-date.
- Updated a few examples to add cache cleanup.
- Confirmed that dependabot is looking for new versions of the dependencies.
Closes #283
> chore: run `examples` in `on-pull-request` workflow

- batchutils/batch_operations.go
This commit corrects the code example in the BatchDeleteError doc comment.
> fix: correct type assertion doc example

- batchutils/batch_operations_test.go
- momento/control_test.go
- momento/dictionary_test.go
- momento/list_test.go
- momento/ping_test.go
- momento/scalar_test.go
- momento/set_test.go
- momento/sorted_set_test.go
- momento/test_helpers/shared_context.go
- momento/topic_client_test.go
This commit adds testing for `CacheClient` instances created using the `NewCacheClientWithDefaultCache` constructor. It focuses on happy path test cases to ensure that the default cache is used when `CacheName` is empty or omitted and that the default cache is overridden when `CacheName` is specified.
> chore: default cache client testing

- auth/credential_provider_test.go
- momento/cache_client.go
- momento/increment.go
- momento/scalar_test.go
- momento/value.go
- responses/increment.go
Added `increment` API along with tests to check:
- if increments from 0 to expected amount with string field
- if increments from 0 to expected amount with bytes field
- if increments with setting and resetting field
Closes #304
> chore: add `increment` API

- config/logger/momento_default_logger/momento-default-logger.go
- examples/pubsub-example/main.go
- internal/grpcmanagers/data_manager.go
- internal/interceptor/stream_retry_interceptor.go
- internal/models/requests.go
- internal/retry/eligibility_strategy.go
- momento/pubsub_client.go
- momento/topic_client.go
- momento/topic_subscribe.go
- momento/topic_subscription.go
- fixes logging format to correctly display timestamp closes #319 
- fixes logging to correctly log traces vs debug vs error ..., and log level string instead of number
- ~~adds stream retry interceptor to retry `subscribe` api call~~
- implements "indefinite retry" for subscriptions who are cancelled
- adds debug logging around stream reconnection
> feat: add support to resubscribe to topics on disconnect

- config/topics_config.go
- config/topics_configurations.go
- internal/grpcmanagers/data_manager.go
- internal/grpcmanagers/topic_manager.go
- internal/models/requests.go
- momento/pubsub_client.go
- momento/test_helpers/shared_context.go
- momento/topic_client.go
- momento/topic_client_test.go
- momento/topic_subscription.go
This commit adds a `maxSubscriptions` configuration option to the topics configuration. This allows users to set an upper limit on the number of subscriptions for a single topic client and allows us to create a sufficient number of channels to handle the subscriber connections.
These changes were verified using a loadgen script that will be added to the SDK in an upcoming PR, which confirmed that > 100 subscriptions were created and reported receiving messages. I was also able to verify using `lsof` that a new network connection to our backend was created for every 100 subscriptions specified via `WithMaxSubscriptions`.
> feat: enable multiple subscription channels

- momento/requester.go
- momento/scalar_test.go
Added details to the issue https://github.com/momentohq/dev-eco-issue-tracker/issues/378
I believe since that issue isn't a part of the repo, Git isn't allowing me to link the PR to that issue.
> fix: return an invalid argument error if the interpreted ttl is 0 milliseconds

- momento/set_if_not_exists.go
- responses/set_if_not_exists.go
Added request and response for ```SetIfNotExists```. Next PR will update the cache client to have the method and the integration tests. I actually did wire the cache client and wrote a vanilla integ test for the new API and it succeeded. Will expand with wholistic tests and have it as a new PR.
> feat: add request and response for set if not exists

- momento/dictionary_length.go
- momento/set_length.go
- momento/sorted_set_length.go
- momento/sorted_set_length_by_score.go
- responses/dictionary_length.go
- responses/set_length.go
- responses/sorted_set_length.go
- responses/sorted_set_length_by_score.go
Added request and response objects for length of sets, sorted sets (by score as well), and dictionary.
> feat: add request and responses for lengths for set, sorted sets, and dict

- batchutils/batch_get.go
- batchutils/batch_set.go
- batchutils/batch_set_test.go
Earlier we used two separate channels in the `batch_get` and `batch_set` operations for results and errors. This had a unwanted side-effect where we couldn't exactly determine when the workers populate the respective channels, and had a minor bug where we didn't take the correct value from one of the channels. This PR changes the two operations to use a single channel for both results and errors, and populate the final responses appropriately. `batch_delete` just uses one channel for errors.
> fix: fix populating results from channel

- batchutils/batch_delete.go
- batchutils/batch_get.go
- batchutils/batch_operations.go
- batchutils/batch_operations_test.go
- batchutils/batch_set.go
- batchutils/batch_set_test.go
This PR adds a `request_timeout` for each individual `set`, `get`, or `delete` calls we make within the batch operations. This is just a hardening mechanism such that one if of the go-routines doesn't hang indefinitely and blocks the entire operation.
> feat: add timeout to individual requests in batch call

- examples/doc-examples-go-apis.go
- examples/pubsub-example/main.go
Addresses the golang task in [#452](https://github.com/momentohq/dev-eco-issue-tracker/issues/452) by using a switch statement to branch on string vs binary received messages.
Addresses the golang part of [#459](https://github.com/momentohq/dev-eco-issue-tracker/issues/459) by adding code snippets for instantiating a topic client, publishing to a topic, and subscribing to a topic. These examples will be used [on this page](https://docs.momentohq.com/develop/api-reference/topics).
> chore: add docs examples for topics and use switch to check message type

- momento/topic_subscription.go
The `getConnectivityState` api is an experimental api. A customer got into a state where the connection thought that it was in a correct connected state, but kept erroring out when trying to receive a message from our service.
This change removes the connectivity state check because
- its an experimental api
- there was no pausing between us saying the connectivity state was in the correct state, and us trying to recieve a message and it failing, causing an infinite loop
I have not been able to reproduce the issue that the customer was facing, but based up the feedback they gave and what I see inside of the code, I believe this should fix their issue
> fix: don't check for connection state when trying to resubscribe

- .github/workflows/test.yml
- Makefile
- batchutils/batch_set_if_not_exists.go
- batchutils/batch_set_test.go
- examples/go.mod
- go.mod
Addresses [#463](https://github.com/momentohq/dev-eco-issue-tracker/issues/463) by adding a client-side implementation of `MSETNX`, named `batchSetIfNotExists` here, as part of the `batchutils` package.
Also corrected a line in the makefile that was preventing `make lint` from working properly.
> feat: add batch set if not exists to batchutils

- internal/grpcmanagers/topic_manager.go
- momento/pubsub_client.go
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/503
Publish and Subscribe now share grpc connections rather than having one for each.
> fix: use just one grpc connection for topics

- config/topics_config.go
- momento/pubsub_client.go
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/529
> feat: use NumGrpcChannels to configure topic client instead of NumMaxSubscriptions

- internal/models/requests.go
- momento/pubsub_client.go
- momento/topic_client.go
- momento/topic_client_test.go
- momento/topic_subscription.go
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/530
Uses an atomic int to count the number of actively used concurrent grpc streams. Allows us to warn users if they are approaching the grpc max concurrent streams limit given the number of grpc channels they have created. Currently warns users if they have <= 10 streams available given a maximum of 100*numGrpcChannels streams.
- Increment before calling `Subscribe`
- Decrement if `Subscribe` returned an error
- Increment before calling `Publish`
- Decrement after calling `Publish`
- Decrement after calling `Close` on a `TopicSubscription`
- Set number of streams to 0 when `Close` is called
> feat: warn users if approaching grpc max concurrent streams limit, add method to close topics subscriptions

- config/config.go
- config/configurations.go
- momento/cache_client.go
Config allows creation of `numGrpcChannels` number of data clients in the CacheClient.
Did local testing and observed in the default case, there's 3 TCP connections (1 control client, 1 data client, 1 ping client). 
When using `WithNumGrpcChannels(4)`, there are 6 TCP connections (1 control client, 4 data client, 1 ping client).
> feat: add number of grpc channels as cache client config

- batchutils/batch_delete.go
- batchutils/batch_get.go
- batchutils/batch_operations.go
- batchutils/batch_set.go
- momento/cache_client.go
The batchutils use a goroutine to distribute items/keys to the
workers for batchget, batchset, batchdelete.
In these goroutines, we have a `select` block in a `for` loop,
which is blocking waiting until the context is closed. However,
in the `default` case of that select block, we try to push a
`nil` onto the channel. This is intended to be a signaling mechanism
to tell the workers that they can exit.
However, this `default` branch of the `select` may be reached
many times between when the workers complete and when the context
is cancelled. If they hit it enough times, they will fill up the
channel to its maximum size, and enter into a blocking state
where they are trying to push another `nil` onto the channel even
after all of the workers have exited. This push will never succeed
because …
> fix: race condition that can cause batchutils to leak goroutines

- batchutils/batch_delete.go
- batchutils/batch_get.go
- batchutils/batch_operations.go
- batchutils/batch_set.go
This commit gets rid of a goroutine in the batch utils functions that is arguably unnecessary.
When we are populating the worker input channels, we were restricting the size of the channel to be only as large as the max number of workers. Then we needed a producer goroutine to feed the keys into that channel as the workers removed them.
However, since the response channel is already sized to handle the entire result set, and the items we put into the input channel are already in memory, sizing the channel so that it is large enough to hold pointers to all of them seems like a reasonable thing to do. It shouldn't increase memory usage much, and it simplifies the code considerably. We get rid of a goroutine and a context that we would otherwise need to be careful about leaking.
> chore: simplify logic of batchutils functions

- momento/cache_client.go
Eager connection failure should return the error instead of logging the failure.
Tested locally and confirmed error is now returned:
```
ClientSdkError: SDK Failed to process the request.
context deadline exceeded
```
> chore: eager connection should fail fast

- config/leaderboard_config.go
- config/leaderboard_configurations.go
- internal/grpcmanagers/leaderboard_manager.go
- internal/models/requests.go
- momento/leaderboard.go
- momento/leaderboard_client.go
- momento/leaderboard_data_client.go
- momento/leaderboard_delete.go
- momento/leaderboard_fetch_by_rank.go
- momento/leaderboard_fetch_by_score.go
- momento/leaderboard_get_rank.go
- momento/leaderboard_length.go
- momento/leaderboard_remove_elements.go
- momento/leaderboard_request.go
- momento/leaderboard_test.go
- momento/leaderboard_upsert.go
- momento/test_helpers/shared_context.go
- momento/value.go
- responses/leaderboard_delete.go
- responses/leaderboard_fetch.go
- responses/leaderboard_length.go
- responses/leaderboard_remove_elements.go
- responses/leaderboard_upsert.go
- utils/validators.go
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/768
* Adds `LeaderboardConfiguration` interface and a default prebuilt config
* `NewLeaderboardClient` creates a `previewLeaderboardClient` struct that contains an internal data client that can be used to interact with multiple leaderboards
* `previewLeaderboardClient`'s `Leaderboard()` method returns a `Leaderboard` object with public-facing APIs (these are called on the Leaderboard object so users don't need to pass in cache name and leaderboard name every time)
* `Leaderboard` object uses provided internal `LeaderboardDataClient` and `LeaderboardGrpcManager` to make requests
* Also added integration tests on par with the [JS sdk tests](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/common-integrat …
> feat: add Momento Leaderboards

- examples/doc-examples-go-apis.go
Fills in missing Go SDK snippets on the [docs API reference page](https://docs.momentohq.com/cache/develop/api-reference)
> chore: add docs snippets for main api reference page

- examples/get-set-batch-perf-test/main.go
- examples/get-set-batch-perf-test/utils/perf-test-options.go
- examples/loadgen/main.go
This commit updates the loadgen and perf test on get/set examples:
- Update the construction of histogram
- Remove the bottleneck that made the get/set channels clogged up due to restriction on the length of channels
- Add worker delay logic to slow down the requests
- Print TPS after every run
> chore: update get/set perf test + loadgen test

- .github/workflows/manual_release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
Previously we ran on macos to sidestep timeouts of uncertain origin on ubuntu-22.04 + GitHub's Azure runners. This has resolved on ubuntu-24.04
> chore: run ci on ubuntu-24.04

- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/manual_release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- momento/topic_subscription.go
If the context that was used to create a subscription is cancelled,
it becomes visible inside the subscription's `Item` function via
`cancelContext.Done()`. However, we were not checking for that
condition when the grpc client's `RecvMsg` function returned,
so after a cancel, we were reconnecting the stream. This made it
impossible to write a goroutine that called this Item function
and then cancel it successfully for a clean shutdown.
This commit adds in some extra logging and an additional case
statement to allow the subscription Item function to exit
when the cancelContext is done.
> fix: Allow subscription to complete when cancelled

- examples/README.md
- examples/go.mod
- examples/go.sum
- examples/topic-example/main.go
- examples/topic-sharded-example/README.md
- examples/topic-sharded-example/main.go
- examples/topic-sharded-example/sharded_topic_client.go
This commit adds a new example in the examples dir; it contains
a drop-in-replacement for the TopicClient that will allow you
to specify a number of shards to split your topic into. Behind
the scenes it will create multiple topics and split up your
messages between them, which can help distribute load more
evenly and improve performance for extremely high-volume topics.
It conforms to the existing TopicClient interface, so it can
be consumed without any code changes beyond the constructor.
> chore: add example for ShardedTopicClient

- momento/topic_client.go
This commit modifies the logic for the initial topic subscription
attempts so that if we get a LimitExceeded error, we will retry
the subscription if there are multiple grpc channels configured.
We try up to one time per channel, on the assumption that we
may get connected to another server where we are still beneath
our subscription limit.
Tested locally against an environment that had 2 servers, with
some code that tries to create 200 subscriptions (with a limit
of 100 per server), and 10 grpc channels. Observed that the first
150-160 usually connected on their first attempt. After that,
began to observe some intermittent retries, but almost always
ended up with 200 successful subscriptions.
> feat: retry initial topic subscriptions on LimitExceeded

- .github/workflows/manual_release.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- CONTRIBUTING.template.md
- batchutils/batch_operations_test.go
- batchutils/batch_set_test.go
- momento/test_helpers/shared_context.go
Unlike the other SDKs, this one still expected an env var named `TEST_AUTH_TOKEN` to `MOMENTO_API_KEY` so this officially switches it over.
Will be more consistent with the other SDKs and will also fix an issue with deploying the golang sdk canary.
> chore: switch from TEST_AUTH_TOKEN to MOMENTO_API_KEY when running tests

- internal/interceptor/first_time_headers_interceptor.go
> fix: lowercase runtime-version and agent headers

- momento/list_caches.go
This PR removes the NextToken from the ListCachesRequest. This parameter was never used; we decided early on to make the user experience simpler for users by avoiding the need to use a while loop to list the caches, and we removed this parameter from the other SDKs. It was unintentionally left in place in the go SDK, so removing it should help users avoid confusion about it and keep user code simple.
This is a technically backward incompatible change. We are coordinating with users to make sure it it safe for them to receive the change before merging it.
> chore: remove NextToken from ListCachesRequest

- momento/cache_client_test.go
- momento/storage_client_test.go
`"storage-client misc"` appeared to be leaking two stores with each run and we might've also been leaking caches this whole time 😱
> fix: make sure to clean up caches and stores that can be leaked in tests

- momento/auth_client_test.go
- momento/internal_auth_client.go
- momento/token_client.go
Addition to https://github.com/momentohq/dev-eco-issue-tracker/issues/954
Found a bug in how GenerateApiKey and GenerateDisposableToken packages the responses ([JS sdk for reference](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/messages/responses/generate-disposable-token.ts#L21-L23)).
This PR fixes the issue by ensuring "api_key" and "endpoint" are included in the b64-encoded object that's passed to the responses' ApiKey field.
> fix: package api key and endpoint correctly in generate token/api key responses

- internal/metadata.go
Prior to this commit we were using a regular `map` object for
keeping track of whether the first-time headers have been
sent for a given client. These `map` objects are not safe for
concurrent access, and will cause the program to crash if there
is a concurrent read while a write is occurring.
This commit switches to a `sync.Map` which is safe for concurrent
access.
> fix: use sync.Map to track first-time agent headers

- Makefile
- momento/auth_client_test.go
- momento/cache_client_test.go
- momento/control_test.go
- momento/dictionary_test.go
- momento/leaderboard_test.go
- momento/list_test.go
- momento/momento_suite_test.go
- momento/permission_scope_test.go
- momento/ping_test.go
- momento/scalar_test.go
- momento/set_test.go
- momento/sorted_set_test.go
- momento/storage_client_test.go
- momento/storage_scalar_test.go
- momento/test_helpers/shared_context.go
- momento/test_helpers/utils.go
- momento/topic_client_test.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/958
Tests were consistently taking anywhere from 18-31 minutes in CI recently. This PR attempts to refactor the tests to speed them up. The tests pass in 3-4 minutes now!
Improvements:
- Uses [BeforeSuite and AfterSuite](https://onsi.github.io/ginkgo/#suite-setup-and-cleanup-beforesuite-and-aftersuite) instead of BeforeEach and AfterEach to initialize test resources (clients, caches, stores, etc). BeforeEach created resources before each "spec" (we have at least 500 specs whereas we have only 3 suites: auth, batchutils, and momento).
- Uses BeforeEach only to provide unique names for topics and collections.
- Adds new helper functions for creating unique string and byte keys.
- Control plane tests that use cache client with …
> chore: clean up and try to speed up tests

- Makefile
We tidy up the Makefile per best practices: group PHONY declarations at the top and add echo statements for each target for clarity.
> refactor: organize makefile phony declarations and add echo statements

- Makefile
Adds per-service targets to the Makefile. Also adds a separate
`install-ginkgo` target that is a prerequisite for any of the test
targets. This prerequisite ensures anyone just wanting to run the
tests has the minimal set of dependencies installed.
In a followup PR we will make per-endpoint targets as well.
> chore: add per-service makefile targets

- momento/scalar_test.go
- momento/topic_client_test.go
Saw several canary test failures from these two tests, likely flaky due to timing issues.
- Relaxed the timing requirement for the scalar test assert statement.
- Relaxed the timeout for the topics test and switched to using `WithCancel` instead of `WithTimeout` for greater clarity.
Checked that removing the context-checking part of `Item()` will make the test fail ([reference comment](https://github.com/momentohq/client-sdk-go/pull/351#discussion_r1313303122) from PR that added this test). I think the intent of this test was to check what happens when a `Item()` is called with a cancelled context (should return err) and I think that's still true after this revision.
> chore: try to make flaky tests less flaky

- Makefile
- batchutils/batch_operations_test.go
- batchutils/batch_set_test.go
- momento/auth_client_test.go
- momento/batch_set_get_test.go
- momento/cache_client_test.go
- momento/control_test.go
- momento/dictionary_test.go
- momento/leaderboard_test.go
- momento/list_test.go
- momento/momento_suite_test.go
- momento/permission_scope_test.go
- momento/scalar_test.go
- momento/set_test.go
- momento/sorted_set_test.go
- momento/storage_client_test.go
- momento/storage_scalar_test.go
- momento/test_helpers/shared_context.go
- momento/topic_client_test.go
Modifies the tests to use labels to identify each service under
test. We then update the makefile to call ginkgo with a label filter,
and can then programmatically detect if (for example) the storage
service is under test. When the storage service is under test, we set
up the test resources. When the storage service is not under test, we
do not do that.
Previously we always stood up storage service test resources, which
caused errors in places where the storage service was not deployed
even if we weren't specifically testing the storage service.
Previously we used the ginkgo `focus` feature to match a regex on
the suite name. As far as I can tell, we cannot access the focus regex
programmatically, hence we use the labels instead. Because of this,
at some point we should consider renaming …
> test: identify services under test w/labels and setup conditionally

- momento/momento_suite_test.go
Previously we matched on the labels of the current spec as opposed to
the label filter passed in from the CLI. This commit uses the correct
syntax as per ginkgo:
https://github.com/onsi/ginkgo/issues/1119#issuecomment-1408996128
> fix: use ginkgo label matching to match on storage filter

- momento/auth_client_test.go
- momento/control_test.go
- momento/dictionary_test.go
- momento/scalar_test.go
- momento/test_helpers/utils.go
Some of the tests weren't using unique test keys. We fix where appropriate. The collection tests still scope a collection name too broadly; we fix the dictionary tests and leave the other collections for future PRs. Importantly we fix the `item get type` and `item get ttl` tests to use unique keys.
> fix: use unique test keys

- momento/topic_client_test.go
Since [Momento Topics do not guarantee order delivery of messages](https://docs.momentohq.com/topics/webhooks/overview#:~:text=Momento%20does%20not%20guarantee%20order%20for%20event%20delivery.), it is possible for the items to go out of sync which seems to be happening with "Publishes and receives detailed subscription items" test (keeps failing in go-lang canary). 
This commit removes the equality check from the test, and rather checks if the received item is one of the elements in expectedValues array.
> fix: detailed sub item test canary error

- momento/scalar_test.go
- momento/topic_client_test.go
`**Test: [topics-service] "Publishes and receives detailed subscription items":**`
The test is failing because it's comparing the first received value (aaa) against the second expected value ([1, 2, 3]), which is causing the mismatch. This mismatch is likely because we have extra non-published items, such as a heartbeat, being included in the receivedItems array. The key issue is that we are not filtering out non-TopicItem events (e.g., TopicHeartbeat, TopicDiscontinuity) before doing the comparison with expectedValues.
Hence, this commit compares only the received **TopicItem values** to the expectedValues. 
`**Test: [cache-service][scalar-tests] "accurately reports the remaining TTL for a key":**`
My hunch is that it can be either of the 3 issues:
1. The TTL might not be exactly what is …
> chore: debug canary tests

- momento/scalar_test.go
Yesterday, I added logging ([PR](https://github.com/momentohq/client-sdk-go/pull/494)) to the cache service scalar test: `accurately reports the remaining TTL for a key` which was failing in go-lang canaries. 
Today, it failed again and I noticed that in the canary environment, original and remaining ttl are exactly equal:
`Original TTL: 2m0s, Remaining TTL: 2m0s`. Therefore, this commit asserts that remaining ttl is `<=` rather than `<` to originally set ttl.
> fix: remaining ttl <= ttl

- Makefile
- momento/scalar_test.go
- momento/set_test.go
[Got error for unexpected results in cell-alpha-dev and cell-privatelink-alpha-dev on 09/10/24 ](https://momento.chronosphere.io/dashboards/canaries?start=3h). 
This commit 
- adds logging to the tests that were failing in the canary.
- pins down the goimports lib version instead of using latest because it was giving the following error in github ci:
```
Run make install-devtools
Installing ginkgo...
go: downloading github.com/onsi/ginkgo/v2 v2.8.1
go: downloading github.com/go-task/slim-sprig v0.0.0-202101071[6](https://github.com/momentohq/client-sdk-go/actions/runs/10798417463/job/29951871882#step:4:7)5309-348f09dbbbc0
go: downloading golang.org/x/tools v0.6.0
go: downloading github.com/google/pprof v0.0.0-2021040[7](https://github.com/momentohq/client-sdk-go/actions/runs/10798417463/jo …
```
> chore: add logging to failing canary tests

- momento/batch_set_get_test.go
- momento/dictionary_test.go
- momento/scalar_test.go
- momento/set_test.go
This commit reduces the ttl on some of the tests. 
For the tests that verify default ttl, adding epsilon sleep durations.
> chore: add epsilon sleep durations/reduce default ttl on tests

- momento/sorted_set_test.go
Saw a canary failure on SortedSetFetchByRank - Remove Elements test today (09/16) at around 7am [(dashboard link)](https://momento.chronosphere.io/dashboards/canaries?start=1726494652000&end=1726495711000)
Error:
```
2024-09-16T13:58:07.277Z
cache-client sortedset-methods SortedSetRemoveElements Removes elements [It] with client with default cache [cache-service]
cache-client sortedset-methods SortedSetRemoveElements Removes elements [It] with client with default cache [cache-service]
2024-09-16T13:58:07.277Z
/.sdks/client-sdk-go/momento/sorted_set_test.go:1459
2024-09-16T13:58:07.277Z
[FAILED] Transform function failed: expected SortedSetFetchHit, but got *responses.SortedSetFetchMiss
```
My hunch is that the key expired from cache till the time it reached the fetch method. 
This commit …
> chore: debug sorted fetch by rank - remove elements test

- examples/topic-example/main.go
This commit updates the topic example to use a waitgroup for the
message polling goroutine(s). This way we can illustrate that the
goroutine exits cleanly after the subscription is closed.
> chore: update topics example to illustrate how to wait for subscription close

- momento/pubsub_client.go
- momento/topic_client.go
- momento/topic_subscription.go
This commit just improves a few things about the logging in the
topic client:
1. Don't log a DEBUG message for every single received item. We
now do this at TRACE, so users can toggle their logger to DEBUG
without being overwhelmed by these.
2. Move a few other important log messages to info/warn for better
visibility.
3. Get rid of some `fmt.Sprintf` interpolations which would cause
minor performance impact even when the log level was set to a higher
value and the log message should not be emitted.
> chore: minor tweaks to logging inside of topic client

- .github/workflows/on-pull-request.yml
- .github/workflows/on-push-to-main.yml
- Makefile
- momento/test_helpers/shared_context.go
Add a flag and make command to use consistent reads in tests. This lets us avoid using them locally, making local development easier.
> chore: Add a flag and make command to use consistent reads in tests

- momento/pubsub_client.go
This commit improves the log message if we detect that a user is trying
to create too many concurrent streams; it adds the current number of streams,
channels, and max number of streams to the log message so that the user
can adjust their configuration.
> chore: improve logging if we exceed the max number of concurrent streams

- CONTRIBUTING.md
- Makefile
We add a makefile target to update the protos from the client protos
repository. Second we update the target to generate the go code from
the protos in light of this. Third we add a target to do both of
these.
We update the CONTRIBUTING file detailing these instructions
> chore: add makefile targets to update and build protos

- .github/workflows/update-and-generate-protos.yml
- Makefile
In order to ensure consistency in the protoc version and the go
plugins version, we install protoc using the script from client-protos
and we pin the go protoc plugins.
We then add a manual workflow that clones the client protos repo at the
latest release; copies protos; generates code; and, if there are any differences, 
opens a PR.
> ci: update protos to latest version

- Makefile
The base file name is `install_protos` not `install-protos`.
> ci: fix typo in install protoc from client protos target

- Makefile
We pin to the previously used version.
> ci: pin protoc-gen-go-grpc to 1.4.0

- Makefile
Run lint after build-protos so that the CI PR passes.
> ci: run lint after build-protos

- .github/workflows/update-and-generate-protos.yml
- Makefile
Updates the `imports` and `staticcheck` targets to ensure the tools
are installed first before running. We update the install targets to
quietly check if installed already, otherwise install.
We do the same for the go proto plugins.
> ci: ensure dev prereqs are installed before running targets

- momento/topic_client.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1020
Added a delay of 500ms between retries if subscription limit is reached (can change the delay if another value would be better). Allowed the loop to retry forever instead of up to a max number of attempts. 
Tested locally and the log message appears to be correctly incrementing the retry attempts and the timing difference appears to be every 500ms as expected.
```
anita@Anitas-Laptop examples % go run topic-example/main.go
[2024-09-26T21:28:13Z] INFO (CacheClient): Creating cache with name: test-cache
[2024-09-26T21:28:13Z] INFO (CacheClient): Cache with name 'test-cache' already exists, skipping
[2024-09-26T21:28:19Z] INFO (topic-client): Topic subscription limit reached, checking to see if subscription is eligible for …
```
> chore: add delay between retries when topic subscription limit is reached

- momento/cache_client_test.go
Canary tests run in much lower latency environments and the `Returns error when eager connection fails` test failed recently, apparently because the client was able to connect in under 1 millisecond. This PR reduces the eager connection timeout to 1 microsecond to try to avoid this test failure in future.
> chore: reduce eager connection timeout for test for low latency test environments

- momento/sorted_set_get_rank.go
- momento/sorted_set_test.go
Previously we did not interpret an element hit vs miss when the sorted
set was found on a sorted set get rank request. In the event a user
queried the rank of an element not present in an existing sorted set,
a rank 0 would be returned.
To correct this we inspect the `result` field, check hit vs miss, and
return a `SortedSetGetRankMiss` on a miss.
> fix: interpret get rank response when sorted set found

- .github/workflows/on-push-to-main.yml
Apparently this step is NOT used after the addition of the release-please workflow and caused major confusion around whether the latest go version was published to gopkg. 
This PR removes the unneeded `publish-golang` step to eliminate this confusion in the future.
> chore: remove unused publish-golang step

- momento/pubsub_client.go
When testing locally, ran into a segfault error when entering the topic resubscribe loop, causing it to panic and not attempt to resubscribe.
This PR adds a nil check that avoids the segfault error:
```
[2024-11-06T22:37:04Z] ERROR (topic-client): stream disconnected YO, attempting to reconnect err:%!(EXTRA string=rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout)
[2024-11-06T22:37:04Z] INFO (topic-client): Attempting reconnecting to client stream
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10337a988]
```
> fix: add nil check before grabbing metadata when retrying subscribe

- internal/retry/eligibility_strategy.go
Based on the current cache service proto, we add in all RPCs. For
maintainability, we arrange them in the same order as in the proto
file. For the RPCs that are new relative to when this was last
updated, add a comment and mark whether they are retryable or not.
> feat: document all rpc's and if they are idempotent or not

- internal/retry/eligibility_strategy.go
Since the client may cancel the context, we do not retry on cancelled
errors. This reverts d62e27d.
> feat: do not retry on cancelled codes

- examples/loadgen/main.go
The previous commit to the loadgen had a typo where we double counted unavailable
instead of adding limit exceeded.
> fix(loadgen): adjust total count in loadgen example

- momento/cache_client.go
- momento/pubsub_client.go
- momento/storage_client.go
- momento/topic_subscription.go
We use atomic writes on several variables in our clients, but did not use atomic reads on them, potentially leading to data race conditions.
This PR updates the variables reads to be atomic variables, such as [`atomic.Uint64`](https://pkg.go.dev/sync/atomic#Uint64), and using first-class atomic methods such as [`Uint64.Load()`](https://pkg.go.dev/sync/atomic#Uint64.Load) and [`Uint64.Add()`](https://pkg.go.dev/sync/atomic#Uint64.Add).
Note: this is different from creating a regular `uint64` variable and then using the [`LoadUint64()`](https://pkg.go.dev/sync/atomic#LoadUint64) method that the godocs say is more error-prone than `atomic.LoadUint64()`.
> fix: use atomic reads when using atomic writes

- momento/get_batch.go
- momento/set_batch.go
Verified that the other streaming method, topic subscribe, already does the nil check before accessing headers and trailers.
Any future server-streaming methods will need to implement this nil check as well
> fix: add nil check before getting header and trailer for GetBatch and SetBatch

- auth/credential_provider.go
- auth/credential_provider_test.go
- internal/grpcmanagers/auth_manager.go
- internal/grpcmanagers/control_manager.go
- internal/grpcmanagers/data_manager.go
- internal/grpcmanagers/grpc-channel-options.go
- internal/grpcmanagers/leaderboard_manager.go
- internal/grpcmanagers/ping_manager.go
- internal/grpcmanagers/store_manager.go
- internal/grpcmanagers/token_manager.go
- internal/grpcmanagers/topic_manager.go
- internal/models/requests.go
- momento/scs_data_client.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1105
Adds `NewMomentoLocalProvider()` method to construct a `CredentialProvider` that allows cache clients to connect to momento-local. To support this, we needed to add a config for allowing insecure connections as momento-local does not use TLS. 
Referenced the structure used in JS sdk (References: [credential provider](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/auth/credential-provider.ts) and [auth utils](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/internal/utils/auth.ts)).
> feat: add CredentialProvider constructor for momento-local connections

- auth/credential_provider.go
- config/config.go
- config/logger/momento_default_logger/momento-default-logger.go
- config/logger/noop-momento-logger.go
- config/transport_strategy.go
- internal/retry/retry.go
- momento/cache_client.go
Logs a pretty printed version of the cache configuration in the cache
client factory function.
When printing the cache configuration before, we would see something like this:
```
&{loggerFactory:0x1400000ee80 transportStrategy:0x1400000ca50 retryStrategy:{eligibilityStrategy:{} maxAttempts:3 log:0x1400000ca68} numGrpcChannels:1 readConcern:balanced}
```
This contains pointers to parts of the configuration that should be dereferenced and recursively represented. We override the `String` function on the appropriate structs to get this. Now we will see:
```
Configuration{loggerFactory=DefaultMomentoLoggerFactory{level=20}, transportStrategy=TransportStrategy{grpcConfig=GrpcConfiguration{deadline=5s, keepAlivePermitWithoutCalls=true, keepAliveTimeout=1s, keepAliveTime=5s, …
```
> chore: log pretty print cache config on instantiation

- momento/retry_test.go
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1107
Adds tests for retry eligibility strategy to match [those in JS sdk](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/client-sdk-nodejs/test/integration/retry/fixed-count-retry-strategy.test.ts).
Additional retry tests will require [middleware](https://github.com/momentohq/client-sdk-go/pull/478) and momento-local-specific middleware be added to the sdk.
> chore: add unit tests for retry eligibility strategy

- config/grpc-configuration.go
- config/topics-grpc-configuration.go
- config/topics_config.go
- config/topics_configurations.go
- config/topics_transport_strategy.go
- internal/grpcmanagers/grpc-channel-options.go
- internal/models/requests.go
- momento/pubsub_client.go
- momento/topic_client.go
- momento/topic_subscription.go
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1124
Under high load, grpc channels that serve both publish and subscribe requests fail to recover when the service redeploys. Creating separate unary and stream grpc channels appears to fix this problem.
Creates separate unary and stream grpc channels within the topic client (defaults to 4 unary and 4 stream channels).
Adds topic config methods `WithNumStreamGrpcChannels()` and `WithNumUnaryGrpcChannels()` to allow overriding the default number. Also adds topics-specific grpc config and transport strategy to the topics config struct to allow setting these values.
Now returns an error if user attempts to start a new subscription when numStreamChannels*100 is exceeded:
```
panic: LimitExceededError: Number of grpc …
```
> feat: configure topic client to use separate publish and subscribe grpc channels

- config/topics_config.go
- internal/grpcmanagers/topic_manager.go
- momento/pubsub_client.go
- momento/topic_client.go
- momento/topic_subscription.go
Ensure the configurable client timeout for topic client is actually used in publish requests.
Refactor the `numGrpcStreams` counter so that each subscription-specific grpc manager keeps count of active streams instead. This ensures that subscribe requests won't get queued up on full grpc channels in edge cases (like retry storms when a server redeploy happens).
As a result, we're able to remove the old "retry subscriptions when limit exceeded error received" stuff from the topic client. 
Tested locally using the basic topic-example program:
<details>
<summary>101 subscriptions and 2 stream channels when cell subscription limit set to default of 100</summary>
```
[2025-03-04T21:00:04Z] DEBUG (topic-client): Starting new subscription on grpc channel 1 which now has 51 streams …
```
> fix: set grpc deadline on publish requests and keep count of active subscriptions in stream topic grpc managers

- momento/topic_client.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1146
Subscribe request should return DeadlineExceeded error if first heartbeat not received within the client timeout duration.
Tested locally (allowed queueing up of subscribe requests again in pubsub client, disabled checks) and received the timeout error as expected when attempting to make 101 subscriptions on 1 grpc channel:
```
[2025-03-12T23:35:07Z] WARN (topic-client): WARNING: approaching grpc maximum concurrent stream limit, 1 remaining of total 100 streams
[2025-03-12T23:35:07Z] WARN (topic-client): WARNING: approaching grpc maximum concurrent stream limit, 0 remaining of total 100 streams
panic: TimeoutError: subscription did not receive first message within the expected time
goroutine 1 [running]:
main.main() …
```
> fix: add topic subscribe timeout

- momento/item_get_ttl.go
- momento/set_if_absent.go
- momento/set_if_absent_or_equal.go
- momento/set_if_equal.go
- momento/set_if_not_equal.go
- momento/set_if_present.go
- momento/set_if_present_and_not_equal.go
- momento/sorted_set_fetch_by_rank.go
- momento/sorted_set_fetch_by_score.go
- momento/sorted_set_get_rank.go
- momento/sorted_set_get_scores.go
- momento/sorted_set_increment_score.go
- momento/sorted_set_put_elements.go
- momento/sorted_set_remove_elements.go
Noticed some inconsistent / incorrect request names on several requester objects. Fixed them so errors will show the correct RPC name
> chore: fix request names in several requester objects

- Makefile
Removes new proto files that are not relevant to SDKs (were added for console work).
Had [caused a build error](https://github.com/momentohq/client-sdk-go/actions/runs/14044961098/job/39323593609) in the "Update and Build Protos" workflow.
> ci: update Makefile to exclude console proto files to fix the proto building workflow

- momento/leaderboard_data_client.go
Before we can update the protos (most recent failure [here](https://github.com/momentohq/client-sdk-go/actions/runs/14045594973/job/39325597158)), we need to remove the CacheName field from leaderboard request bodies as they are read from the "cache" metadata instead as per this [change](https://github.com/momentohq/client-protos/pull/307) in the protos.
> chore: remove cache name field from leaderboard requests

- momento/cache_client.go
- momento/get_with_hash.go
- momento/set_if_absent_or_hash_equal.go
- momento/set_if_absent_or_hash_not_equal.go
- momento/set_if_present_and_hash_equal.go
- momento/set_if_present_and_hash_not_equal.go
- momento/set_with_hash.go
- responses/get_with_hash.go
- responses/set_if_absent_or_hash_equal.go
- responses/set_if_absent_or_hash_not_equal.go
- responses/set_if_present_and_hash_equal.go
- responses/set_if_present_and_hash_not_equal.go
- responses/set_with_hash.go
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1198
Confirmed the APIs work as expected against alpha using the tests in https://github.com/momentohq/client-sdk-go/pull/612, but the tests will be merged at a later date to avoid unnecessary canary failures.
We should align on naming and any other public API implications on this PR:
- Use the proto names (e.g. SetIfPresentAnd**NotHashEqual**) or rearrange a little (e.g. SetIfPresentAnd**HashNotEqual**)?
- Unconditional get and set with hash names: GetWithHash and SetWithHash
> feat: add new get/set if hash apis

- config/retry/exponential_backoff_retry_strategy.go
- config/retry/fixed_count_retry_strategy.go
- config/retry/fixed_timeout_retry_strategy.go
- config/retry/legacy_topic_subscription_retry_strategy.go
- config/retry/never_retry_strategy.go
- config/retry/retry.go
- internal/grpcmanagers/data_manager.go
- internal/interceptor/retry_interceptor.go
- momento/retry_test.go
- momento/test_helpers/momento_local_middleware.go
- momento/test_helpers/momento_local_middleware_request_handler.go
- momento/test_helpers/retry_metrics_collector.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1205
- Adds FixedTimeoutRetryStrategy and tests
- Updated timestamp collection to be unix time in milliseconds instead of seconds to better support the new tests
- Fix: momento-local middleware was sending metadata header `delay-millis` instead of `delay-ms`
Because go sdk uses context.WithTimeout / context.WithDeadline instead of a grpc call option, we are responsible for catching a retry's deadline exceeded error and passing along a new context object with updated deadline.
> feat: add FixedTimeoutRetryStrategy and tests

- config/retry/exponential_backoff_retry_strategy.go
- config/retry/fixed_count_retry_strategy.go
- config/retry/fixed_timeout_retry_strategy.go
- config/retry/legacy_topic_subscription_retry_strategy.go
- config/retry/never_retry_strategy.go
- config/retry/retry.go
- internal/interceptor/retry_interceptor.go
Realized that adding [`CalculateRetryDeadline`](https://github.com/momentohq/client-sdk-go/blob/main/config/retry/retry.go#L29) to the retry strategy interface would break backwards compatibility. 
We haven't cut a release with this addition yet; this PR will fix the breaking change so that we avoid a release with a breaking change.
The safer thing to do is to make a new `DeadlineAwareRetryStrategy` interface that the retry interceptor can check for and that the `FixedTimeoutRetryStrategy` can implement instead.
> fix: revise retry strategy interface additions to maintain backwards compatibility

- examples/aws-lambda/README.md
- examples/aws-lambda/infrastructure/lib/momento-lambda-stack.ts
- examples/aws-lambda/infrastructure/package-lock.json
- examples/aws-lambda/infrastructure/package.json
- examples/aws-lambda/lambda/main.go
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1224
Updated the lambda example to re-use the cache client after initialization.
Tested locally and also had to upgrade some dependencies to avoid warnings / deprecation notices.
> chore: reuse cache client in aws lambda example and update deps

- Makefile
- config/middleware/impl/compression_test.go
- config/middleware/impl/test_helpers/compression_test_helpers.go
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1223
Follow-up work to adding compression middleware in the sdk.
Created a test-specific gzip middleware that uses channels to verify data is actually getting compressed and decompressed in tests.
> chore: improved gzip compression tests

- config/middleware/impl/compression_test.go
- config/middleware/impl/test_helpers/compression_test_helpers.go
Follow-up to #641 and closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1223
Remove unused test helper property and DRY up tests
> chore: clean up gzip compression tests

- momento/cache_client.go
This will prevent leaked goroutines from the cache client
> fix: make sure cache client closes all underlying clients upon close

- momento/scs_data_client.go
Added debug logs to makeRequest so that all methods report any errors they see. 
Log output looks like this: 
`[2025-09-04T21:59:30Z] DEBUG (data-client): context created with timeout=5s`
`[2025-09-04T21:59:31Z] DEBUG (fixed-count-retry-strategy): Request is not retryable: [method: /cache_client.Scs/DictionarySet, status: NotFound]`
`[2025-09-04T21:59:31Z] ERROR (data-client): gRPC request failed: rpc error: code = NotFound desc = Cache not found, responseMetadata=[map[] map[access-control-allow-credentials:[true] access-control-expose-headers:[grpc-status,grpc-message,grpc-encoding,grpc-accept-encoding,err] content-type:[application/grpc] date:[Thu, 04 Sep 2025 21:59:30 GMT] err:[momento_general_err] vary:[origin, access-control-request-method, access-control-request-headers]]]
panic: …
> chore: Adding Debug Logs
